/**
 * Image discovery module — reads from pre-computed static manifest.
 * NO runtime fs dependency. Safe for Vercel serverless functions.
 * 
 * Manifest is generated by: `node scripts/build-image-manifest.js`
 * Run it before `next build` (configured in package.json prebuild).
 */

import imageManifest from '@/config/image-manifest.json';

type ImageManifest = Record<string, { mockups: string[]; screenshots: string[] }>;
const manifest = imageManifest as ImageManifest;

/**
 * Discovers mockup images for a given project.
 */
export function getMockupImages(title: string, slug: string, imageDir?: string): string[] {
  const dirName = findDirName(imageDir || title, slug);
  if (!dirName || !manifest[dirName]) return [];
  return manifest[dirName].mockups;
}

/**
 * Discovers screenshot images for a given project.
 */
export function getScreenshotImages(title: string, slug: string, imageDir?: string): string[] {
  const dirName = findDirName(imageDir || title, slug);
  if (!dirName || !manifest[dirName]) return [];
  return manifest[dirName].screenshots;
}

/**
 * Returns ALL images (mockups + screenshots combined).
 */
export function getAllProjectImages(title: string, slug: string, imageDir?: string): string[] {
  return [...getMockupImages(title, slug, imageDir), ...getScreenshotImages(title, slug, imageDir)];
}

function findDirName(title: string, slug: string): string | undefined {
  // Direct match first
  if (manifest[title]) return title;

  // Fuzzy match
  const dirs = Object.keys(manifest);
  return dirs.find(dir => {
    const normDir = dir.toLowerCase().replace(/[^a-z0-9]/g, '');
    const normTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '');
    const normSlug = slug.toLowerCase().replace(/[^a-z0-9]/g, '');
    return normDir.includes(normSlug) || normSlug.includes(normDir) || normTitle.includes(normDir) || normDir.includes(normTitle);
  });
}
